# Project
version=1.0.1
mod_group_id=com.christofmeg.megaenderdrives
java_version=21

# Mod options
minecraft_version=1.21.1
mod_name=MEGA Ender Drives
mod_authors=Christofmeg
mod_id=megaenderdrives
mod_license=The MIT License (MIT)
mod_description=MEGA variants of Ender Drives
minecraft_version_range=[1.21.1]

# NeoForge | https://projects.neoforged.net/neoforged/neoforge
neoforge_supported_versions=1.21.1
neo_version=21.1.209
loader_version_range=[1,)

# Parchment | https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# CurseForgeGradle | Minotaur options
cf_id=1359245
modrinth_id=AWma6PJd
release_type=release
neoforge_release_versions=1.21.1